### ISSUE TITLE
Stall after [bumphunterEngine] Smoothing coefficients.

### ISSUE THREAD

**Issue by rrydbirk** [rafalab/bumphunter#24]
I'm running bumphunter as integrated in ChAMP (champ.Block) with 20 cores, 100 GB mem. It's stalling at

[bumphunterEngine] Smoothing coefficients.

Input is 224 clusters, and I'm smoothing with loessByCluster. I don't know if 224 clusters is a lot, does that explain why the process stalls? How long should I expect this step to take?

**Comment by rrydbirk** [comment]
I've had it running overnight with even more cores, this is where I got to after 18 hours:

[===========================]
[<<<< ChAMP.Block START >>>>]
-----------------------------
Running with 80cores.
Loading required package: IlluminaHumanMethylationEPICanno.ilm10b4.hg19
<< Load Annotation Successfully >>
<< Get Clusters by cgi-info Successfully >>
<< Calculate Average Beta Value Successfully >>
<< Generate Block Position Successfully >>
<< 224 clusters are generated for blocks >>
<< Generate information for New Clusters >>
[bumphunterEngine] Parallelizing using 80 workers/cores (backend: doParallelMC, version: 1.0.14).
[bumphunterEngine] Computing coefficients.
[bumphunterEngine] Smoothing coefficients.

**Comment by rrydbirk** [comment]
Closed due to inactivity

**Comment by BenjaminDEMAILLE** [comment]
Same problem
